name: Publish Python Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install build twine bump2version

    - name: Bump version and tag
      id: bump_version
      run: |
        # Bump the version, create a new tag, and update the repository
        bump2version patch --allow-dirty --list
        git push origin --tags
        echo "Version bumped to ${{ steps.bump_version.outputs.new_version }}"

    - name: Build the package using `build`
      run: |
        python -m build

    - name: Create a release folder
      run: |
        mkdir -p release
        cp dist/* release/
        echo "Release folder created with distribution files"

    - name: Commit and push release folder
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add release
        git commit -m "Add release files for version $(python -c 'import mylibrary.version as v; print(v.__version__)')"
        git push origin main

    - name: Publish to PyPI
      run: |
        twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
