name: Version Bump in Major Branches

on:
  push:
    branches:
      - '0.*'
      - '1.*'
      - '2.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install build twine

      - name: Configure Git user
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Determine Version Type
        id: version_type
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ "[major]" ]]; then
            echo "version_type=major" >> $GITHUB_ENV
          elif [[ "${{ github.event.head_commit.message }}" =~ "[minor]" ]]; then
            echo "version_type=minor" >> $GITHUB_ENV
          else
            echo "version_type=patch" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Bump version
        id: bump_version
        uses: callowayproject/bump-my-version@master
        with:
          args: ${{ env.version_type }}  # Use the version type (major, minor, patch)
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Token to commit the version bump

      - name: Check if version was bumped
        if: steps.bump_version.outputs.bumped == 'true'
        run: |
          echo "Version was bumped from ${{ steps.bump_version.outputs.previous-version }} to ${{ steps.bump_version.outputs.current-version }}!"

      - name: Build the package
        run: |
          python -m build

      - name: Publish to PyPI
        run: |
          twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

      - name: Prepare release artifacts
        run: |
          # Create a tarball with build artifacts
          tar -czvf release.tar.gz dist/*.tar.gz dist/*.whl

      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.bump_version.outputs.current-version }}            # Tag with the new version
          name: Release v${{ steps.bump_version.outputs.current-version }}   # Release name with the new version
          artifacts: "release.tar.gz,dist/*.tar.gz,dist/*.whl"   # Specify the artifacts to upload
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push version tag to GitHub
        run: |
          # Ensure the push goes to the branch (e.g., 0.x, 1.x)
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin ${{ github.ref }} --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

